# Generated by Django 4.2.21 on 2025-05-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("spendings", models.FloatField(default=0)),
                ("spending_description", models.TextField(blank=True, null=True)),
                ("received", models.FloatField(blank=True, default=0, null=True)),
                ("received_description", models.TextField(blank=True, null=True)),
                ("invested", models.FloatField(default=0)),
                ("invested_description", models.TextField(blank=True, null=True)),
                ("fd_incoming", models.FloatField(default=0)),
                ("fd_outgoing", models.FloatField(default=0)),
                ("current_fd", models.FloatField(default=0)),
                ("axis_savings", models.FloatField(default=0)),
                ("union_savings", models.FloatField(default=0)),
                ("kotak_savings", models.FloatField(default=0)),
                ("grow_pnl", models.FloatField(default=0)),
                ("grow_wallet", models.FloatField(default=0)),
                ("mutualfund_pnl", models.FloatField(default=0)),
                ("kite_pnl", models.FloatField(default=0)),
                ("kite_wallet", models.FloatField(default=0)),
                ("trading_pnl", models.FloatField(default=0)),
                ("wint_wealth", models.FloatField(default=0)),
                ("nps", models.FloatField(default=0)),
                ("epfo", models.FloatField(default=0)),
                ("loan_given", models.FloatField(default=0)),
                ("home_spendings", models.FloatField(default=0)),
                ("home_spend_description", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
